### ISSUE TITLE
ارسال نوتیفیکیشن در .net

### ISSUE THREAD

**Issue by mohammadTaghy** [chabokpush/chabok-client-wp#1]
سلام.
من از onesignal استفاده می کردم اما چون تحریم کرده دارم کوچ می کنم به چابک.
اما نمیفهمم چطور از .net نوتیفیکیشن بفرستم و مستندات که خوندم بیشتر گیج شدم.امکانش هست من را راهنمایی کنید؟
با سپاس

**Comment by Husseinhj** [comment]
شما برای چه پلتفری از دات نت نیاز به پوش دارین؟
ویندوز، ویندوز فون، ویندوز فورم و...

**Comment by mohammadTaghy** [comment]
android & ios
برای این دو پلتفرم می خواهم نوتیف ارسال کنم

**Comment by Husseinhj** [comment]
<div dir='rtl'>
خب پس شما backend دات نت دارین درسته؟
پس مشکلی ندارین 

برای اندروید داک زیر رو مطالعه کنین :
</div>
https://doc.chabokpush.com/android/required.html
<div dir='rtl'>
برای ای او اس داک زیر رو مطالعه کنین :
</div>
https://doc.chabokpush.com/ios/required.html
<div dir='rtl'>
برای استفاده از رست‌های ما هم از صفحه زیر استفاده کنین:
</div>
https://api.doc.chabokpush.com/
<div dir='rtl'>
برای رست باید access_token رو به authorization بدین و try it out رو بزنین
</div>

**Comment by mohammadTaghy** [comment]
فکر می کنم سؤتفاهم شد من می خواهم از .net برای کلاینت اندروید و آی او اس  نوتیفیکیشن ارسال کنم.
این document هایی که شما دادین برای ارسال از موبایل به موبایل

**Comment by amir-yaghoubi** [comment]
<div dir="rtl">
داکیومنت‌های <a href="https://doc.chabokpush.com/android/required.html">اندروید</a> و <a href="https://doc.chabokpush.com/ios/required.html"> ios</a> ارسال شده توسط همکارم به منظور فعال‌سازی چابک بر روی دستگاه‌های مذکور می‌باشد.
</div>
<div dir="rtl">
به منظور ارسال پیام از سمت سرور خود می‌توانید از <b>Rest api</b> تعبیه شده استفاده نمایید.
توضیحات بیشتر در این قسمت از <a href="https://api.doc.chabokpush.com/#/push/">مستندات</a> می‌باشد.
</div>

**Comment by mohammadTaghy** [comment]
بله
یعنی به جز حالت json حالت دیگه ایی برای ارسال ندارید
بعد من بخوام یک پیام به یک گوشی بفرستم بدون کانال امکانش هست؟

**Comment by amir-yaghoubi** [comment]
> یعنی به جز حالت json حالت دیگه ایی برای ارسال ندارید

<div dir="rtl">
خیر، درحال حاضر ارتباط از سرور شما با سرور ما تنها با rest api و webhook صورت می‌پذیرد
</div>

> بعد من بخوام یک پیام به یک گوشی بفرستم بدون کانال امکانش هست؟
<div dir="rtl">
خیر، کانال راه ارتباطی شما با دستگاه مروبطه هست. در صورتی که فیلد کانال را خالی بگذارید مقدار پیش‌فرض آن کانال <code>default</code> می‌باشد.
</div>

**Comment by mohammadTaghy** [comment]
بسیار ممنون
آیا امکان ارسال به چند کاربر با یک سرویس موجود می باشد؟
در این صورت باید چگونه تمام user ها را به json بدهم؟
ایا می توان به این json ارایه ای از user داد؟

**Comment by amir-yaghoubi** [comment]
> آیا امکان ارسال به چند کاربر با یک سرویس موجود می باشد؟

بله شما می‌توانید با استفاده از endpoint `push/byQuery` به چندین کاربر پیام ارسال نمایید.
به طور مثال:
```json
{
  "target": {
    "and": [
      {
        "deviceType": "android"
      },
    ],
  },
  "channel": "default",
  "notification": {
    "title": "نوتیف تستی",
    "body": "این یک پیام تستی از سمت چابک می‌باشد",
    },
  "content": "تست",
  "inApp": false,
  "alertText": "string"
}
```
json بالا باعث ارسال نوتیف تستی به تمام کاربران اندروید شما می‌شود.

با تغییر محتویات قسمت `target` شما می‌توانید محدوده کاربران خود را تغییر دهید.

> ایا می توان به این json ارایه ای از user داد؟

در صورتی که میخواهید به یک آرایه از کاربران خود پیام ارسال کنید با استفاده از endpoint `push/toUsers` و فراهم آوردن یک آرایه از تنظیمات پوش دلخواه خود می‌توانید پوش را ارسال نمایید.

```json
[

  {
    "user": "my-user-1",
    "channel": "default",
    "content": "تست",
    "inApp": false,
    "live": false,
    "ttl": 0,
    "notification": {
    "title": "نوتیف تستی",
    "body": "تست"
    },
    "contentType": "تست",
  },
  {
    "user": "my-user-2",
    "channel": "default",
    "content": "تست",
    "inApp": false,
    "live": false,
    "ttl": 0,
    "notification": {
    "title": "نوتیف تستی",
    "body": "تست"
    },
    "contentType": "تست",
  }

]
```

**Comment by amir-yaghoubi** [comment]
<div dir="rtl">
من این issue رو می‌بندم، اگه همچنان سوالی در این مورد داشتین دوباره باز کنین.
</div>

**Comment by mohammadTaghy** [comment]
بسیار سپاسگذارم

**Comment by amir-yaghoubi** [comment]
خواهش میکنم

**Comment by mohammadTaghy** [comment]
سلام
مقادیر sound در notification چه چیزهایی می تواند باشد؟
الان نوتیفیکیشن های من بی صدا است
