### ISSUE TITLE
مقادیر ممکن برای sound در notification

### ISSUE THREAD

**Issue by mohammadTaghy** [chabokpush/chabok-client-wp#2]
سلام
مقادیر sound در notification چه چیزهایی می تواند باشد؟
الان نوتیفیکیشن های من بی صدا است
اگر document در این مورد هست معرفی کنید لطفا

**Comment by mohammadTaghy** [comment]
لطفا راهنمایی کنید

**Comment by Husseinhj** [comment]
شما برای ویندوزفون یا ویندوز یونیورسال ۱۰ نیاز به صدا نوتفیکیشن دارید؟
اگر اندروید یا ای‌او‌اس منظورتون هست. لطفا ایشو مربوط به هر ریپازیتوری رو برای همون ریپازیتوری بزنید. در صورتی که ایشو مرتبط با ریپازیتوری باشد پاسخ داده خواهد شد

**Comment by mohammadTaghy** [comment]
نه از سرور برای کلاینت اندروبد نوتیفیکیشن ارسال می کنم صدا ندارد

**Comment by Husseinhj** [comment]
ایشو رو می‌بندم. لطفا ایشو خودتون رو [ریپازیتوری اندروید ](https://github.com/chabokpush/chabok-client-android/issues)بنویسید.
سوال شما قبلا در[ ریپازیتور اندروید و در ایشو 3](https://github.com/chabokpush/chabok-client-android/issues/3) پاسخ داده شده.

**Comment by mohammadTaghy** [comment]
بسیار ممنون
