### ISSUE TITLE
چرا نوتیف ابتدایی پیام خود من نیست؟

### ISSUE THREAD

**Issue by mohammadTaghy** [chabokpush/chabok-client-wp#3]
با سلام
زمانی که من نوتیف میزنم به موبایل موقعی که اپلیکیشن بسته است یک پیام پیشفرض با متن:پیام جدید از اپلیکیشن دارید
می دهد
چرا پیام مستقیم من را نمایش نمی دهد زمانی که اپلیکیشن بسته است؟

**Comment by Husseinhj** [comment]
روی چه پلتفرمی تست می‌کنید؟

**Comment by mohammadTaghy** [comment]
بک اند روی .net
و پلتفرم موبایل ios

**Comment by Husseinhj** [comment]
لطفا ایشو خودتون رو  ریپازیتوری مرتبط ثبت کنید :
بک‌اند (موقتا) : https://github.com/chabokpush/chabok-php-demo/issues
اندروید : https://github.com/chabokpush/chabok-client-android/issues
ای‌او‌اس : https://github.com/chabokpush/chabok-client-ios/issues

من این ایشو رو می‌بندم این ریپازیتوری برای ویندوزفون و ویندوز یونیورسال می‌باشد.

**Comment by mohammadTaghy** [comment]
بسیار ممنون
دایکیومنت را دقیق تر مطالعه کردم و متوجه شدم که با useAsAlert=true
می توان متن را در alert نمایش گذاشت
